### ISSUE TITLE
CTags support

### ISSUE THREAD

**Issue by lunaryorn** [lunaryorn/.emacs.d#19]
Add ctags support.

Load tags from `.git` for [compatibility with fugitive](http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html).

**Comment by lunaryorn** [comment]
I've no need for ctags

**Comment by ivanbrennan** [comment]
@lunaryorn I'm curious what you use in place of ctags. I've been migrating over from Vim, and it's been a bumpy ride finding a tags solution.

I'd been using tpope's git hook approach (linked above) previously, so the first thing I tried was adapting that to [etags](https://github.com/ivanbrennan/dotfiles/blob/master/git/templates/hooks/etags), but I couldn't find a way to get Emacs to automatically locate the tags under `.git/`, short of adding a bunch of hard-coded paths to `tags-table-list`.

I've ended up using GNU global configured with ctags as a backend parser, and [ggtags.el](https://github.com/leoliu/ggtags). I gave up (for now) trying to keep my tags files under `.git/`, but I'm still leveraging [git hooks](https://github.com/ivanbrennan/dotfiles/blob/master/git/templates/hooks/gtags) to generate them.

I'm sure it depends which languages you work in most, but what do you recommend when it comes to tags/navigation?

**Comment by lunaryorn** [comment]
@ivanbrennan I'm no longer using Emacs, and do not longer follow Emacs packages.  I'm just not interested anymore, so please understand that I'll not recommend anything, and that I'm not interested in talking about what's available these days.

I'm sorry but I cannot help you; if you're interested in what I used to use take a look at `init.el`, it's all in there.

**Comment by ivanbrennan** [comment]
Ok, thanks @lunaryorn
