### ISSUE TITLE
keyboard-cat-mode should be on melpa

### ISSUE THREAD

**Issue by wbolster** [lunaryorn/.emacs.d#35]
you are doing the community a great disservice by not providing a keyboard-cat-mode package on melpa.

please

- make a separate github repo containing the keyboard cat elisp file
- add a proper autoload cookie for `(keyboard-cat-mode)`
- fork melpa, add a recipe, and open a pr

please think of the kittens.

**Comment by lunaryorn** [comment]
I'm sorry but are you sure that you've been reporting this to the right repo? I'm not aware that there's any such mode in my configuration.

**Comment by wbolster** [comment]
yeah, you're right. sorry for the noise. it was intended for someone else.  (i had multiple github browser tabs with other people's emacs configs open, that's why it happened.)

**Comment by lunaryorn** [comment]
Never mind. Good luck with this.
