### ISSUE TITLE
Query: Calendar and time packages share the same binding

### ISSUE THREAD

**Issue by doolio** [lunaryorn/.emacs.d#36]
Learning a lot from your configuration. The configuration for both 'calendar' and 'time' share the same binding namely "C-c a c". Invoking it shows the defined world clock. Perhaps the binding for `time' is meant to be "C-c a t"?

**Comment by lunaryorn** [comment]
Thanks for the kind words, and doubly so for making me aware of this flaw :blush:

Indeed I messed up the bindings, but I wanted to use `C-c a C` for the time (`c` for clock).  `C-c a t` is already taken for `shell`.

**Comment by doolio** [comment]
Yes, you're right and `C-c a C` keeps it consistent with the calendar binding for a date/time application which is nice. I think as well there may be a conflict with `C-C t r` for `writeroom-mode` and `rainbow-mode`.

**Comment by lunaryorn** [comment]
@doolio Thanks again :blush:

Fixed both 😎
