### ISSUE TITLE
Could you share why aren't you using emacs anymore?

### ISSUE THREAD

**Issue by ZzAntares** [lunaryorn/.emacs.d#39]
Hi, I'm just interested, after the great packages you've developed why did you change to nvim? I'm just curious since I came from vim and while nvim is great I think is not yet as good as Emacs. Looked in your blog but I didn't see a post about it.

Thanks.

**Comment by lunaryorn** [comment]
See #38

**Comment by ZzAntares** [comment]
Ok, that doesn't answer my inquiry, but it's your right not to answer (although I don't see why the fuzz).

Thanks!

**Comment by lunaryorn** [comment]
I'm sorry. Keep your eyes and ears open in the Emacs community, try to approach it from my point of view—Ive written one or two posts about it—and perhaps in time you'll understand why I prefer to leave Emacs behind and not speak about the matter any more.

**Comment by ZzAntares** [comment]
👍

**Comment by lunaryorn** [comment]
Thanks your interest ❤️
